quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Animaker": [0.6, 0.7]
    "Vyond": [0.8, 0.9]
    "Lumen5": [0.7, 0.6]
    "Biteable": [0.5, 0.8]
    "InVideo": [0.6, 0.7]
    "Moovly": [0.4, 0.5]
    "Powtoon": [0.7, 0.7]
    "Our Target Product": [0.6, 0.7]
